export function generateHtmlReport(data) {
  const {
    total,
    success,
    failure,
    avg,
    p95,
    rps,
    elapsedSec,
    memory,
    codes,
    endpoints
  } = data;

  return `
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <title>Loadly Report</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <style>
    body {
      font-family: Inter, Arial, sans-serif;
      margin: 0;
      padding: 0;
      background: #f5f6fa;
      color: #1a1a1d;
    }

    .container {
      max-width: 960px;
      margin: 30px auto;
      padding: 20px;
    }

    h1 {
      font-size: 32px;
      margin-bottom: 4px;
      color: #0a0a23;
    }

    h2 {
      font-size: 22px;
      margin-top: 32px;
      color: #0a0a23;
    }

    .subtitle {
      font-size: 14px;
      color: #6b6b6b;
      margin-bottom: 20px;
    }

    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
      gap: 16px;
      margin-top: 20px;
    }

    .card {
      background: white;
      border-radius: 12px;
      padding: 16px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.08);
      border: 1px solid #e3e7ee;
    }

    .card-title {
      font-size: 13px;
      color: #6d6d72;
      margin-bottom: 6px;
      font-weight: 500;
    }

    .card-value {
      font-size: 22px;
      font-weight: 600;
      color: #111;
    }

    pre {
      background: #111827;
      color: #d1e7ff;
      padding: 14px;
      border-radius: 12px;
      overflow: auto;
      font-size: 14px;
      margin-top: 10px;
    }

    .endpoint {
      background: white;
      padding: 12px 16px;
      border-radius: 10px;
      border: 1px solid #e3e7ee;
      margin-bottom: 10px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .endpoint-method {
      padding: 4px 10px;
      border-radius: 6px;
      font-weight: 600;
      color: white;
    }

    .method-GET { background: #10b981; }
    .method-POST { background: #3b82f6; }
    .method-PUT { background: #f59e0b; }
    .method-DELETE { background: #ef4444; }

    footer {
      text-align: center;
      margin: 40px 0;
      font-size: 13px;
      color: #777;
    }
  </style>
</head>

<body>
  <div class="container">

    <h1>Loadly Test Report</h1>
    <div class="subtitle">Lightweight API load testing with live analytics</div>

    <h2>Overview</h2>
    <div class="grid">
      ${metricCard("Total Requests", total)}
      ${metricCard("Success", success)}
      ${metricCard("Failures", failure)}
      ${metricCard("RPS (req/sec)", rps.toFixed(2))}
      ${metricCard("Avg Latency (ms)", avg.toFixed(2))}
      ${metricCard("p95 Latency (ms)", p95.toFixed(2))}
      ${metricCard("Elapsed (s)", elapsedSec.toFixed(1))}
      ${metricCard("RSS (MB)", (memory.rss / 1024 / 1024).toFixed(1))}
      ${metricCard("Heap (MB)", (memory.heapUsed / 1024 / 1024).toFixed(1))}
    </div>

    <h2>Endpoints Tested</h2>
    ${endpoints
      ?.map(
        (e) => `
      <div class="endpoint">
        <div class="endpoint-method method-${e.method}">
          ${e.method}
        </div>
        <div style="margin-left: 12px; font-weight: 500;">${e.url}</div>
      </div>
    `
      )
      .join("")}

    <h2>Status Codes Distribution</h2>
    <pre>${JSON.stringify(codes, null, 2)}</pre>

    <h2>Memory Footprint</h2>
    <pre>${JSON.stringify(memory, null, 2)}</pre>

    <footer>
      Generated by Loadly — ${new Date().toLocaleString()}
    </footer>
  </div>
</body>

</html>`;
}

// Helper to generate cards
function metricCard(label, value) {
  return `
  <div class="card">
    <div class="card-title">${label}</div>
    <div class="card-value">${value}</div>
  </div>`;
}
